# Generated by Django 2.0 on 2017-12-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Categories'},
        ),
    ]
